### ISSUE TITLE
shape.getBounds() ignores the bounds of the cache

### ISSUE THREAD

**Issue by evgeniyaaa** [CreateJS/EaselJS#915]
I've updated the code with the new version of EaslJS (Version 1.0.0).

In the new version, objects that have been cached **do not return** the bounds of the cache, when using getBounds().

``` javascript
var graphics = new createjs.Graphics().beginFill("#ff0000").drawRect(0, 0, 100, 100);
var shape = new createjs.Shape(graphics);
shape.cache(0, 0, 100, 100);

/* NOW (Version 1.0.0) */
shape.getBounds(); // {x: 0, y: 0, width: 0, height: 0} 

/* BEFORE (Version 0.8.2) */
shape.getBounds(); // {x: 0, y: 0, width: 100, height: 100}
```

In order to fix that I have to add one more extra line after the cache with setBounds(), which is a lot of work to do across all the code.

``` javascript
shape.setBounds(0, 0, 100, 100);
```

**Comment by sebastianderossi** [comment]
@evgeniyaaa Good catch! This issue will be corrected on our next build. Thanks! As a workaround, you could use `shape.bitmapCache` which will return `{width:100, height:100, x:0,y:0}`

**Comment by JonnyCodes** [comment]
I'm new to EaselJS and just figuring things out.
I thought it didn't calculate bounds of shapes or does it just do simple shapes?
I've been digging through the code and I don't see where it updates the bounds when drawing shapes, could someone point me in the right direction?

**Comment by sebastianderossi** [comment]
Hi @JonnyCodes 
Here is some information you'll find useful: 

- [DisplayObject getBounds()](https://createjs.com/docs/easeljs/classes/DisplayObject.html#method_getBounds)

- [Blog Article - Width and Height in EaselJS](http://blog.createjs.com/update-width-height-in-easeljs/)

**Comment by phesterman** [comment]
What if the bounds is something like: {x: -5, y: -20, width: 100, height: 100} before the object is cached?  The new bounds is returned as {x: 0, y: 0, width: 100, height: 100}.

**Comment by heaversm** [comment]
Are we sure this has been fixed? I'm using 2.0 beta 4, and bounds returns zero. I noticed that `el.children[0].bitmapCache` contains the useful width and height that I'm after.

**Comment by lacek** [comment]
@heaversm I don't think `2.0.0-beta.4` contains the fix yet. The NPM page shows that the version was released at 2018-11-21 23:30:20. But this fix was merged at later time (90a4ee6). Thus you're still having the issue. You will have to wait for another release to include the fix.

If you really need to use version 2 at this time, you may consider using a specific commit from branch 2.0 by specifying the dependency version as [GitHub URL](https://docs.npmjs.com/files/package.json#github-urls) in your `package.json`, e.g. `CreateJS/EaselJS#cb1fbba` instead of `2.0.0-beta.4`.
