### ISSUE TITLE
[Bug] Chrome 70 touch no longer triggers mousedown, pressmove, pressup

### ISSUE THREAD

**Issue by masandoval** [CreateJS/EaselJS#997]
### Issue Details
* Version used: 1.0.2 

* Touch events in Chrome no longer trigger DisplayObject mousedown, pressmove, or pressup events, except when performing a click (i.e. single tap), which triggers mousedown and pressup on release.

* This also happens on the Mouse Interaction tutorial page: https://www.createjs.com/tutorials/Mouse%20Interaction/
  * See the Stage Mouse Events and Drag and Drop examples.

* OS and browser: Chrome 70.0.3538.76 on Chromebook and Windows Surface.

* Do you know of any workarounds?
  * Reverting to Chrome 69 "fixes" the issue.

**Comment by masandoval** [comment]
Adding
```
			ls["pointerup"] = {t:t, f:function(e) { _this._handleMouseUp(e)} };
			ls["pointermove"] = {t:t, f:function(e) { _this._handleMouseMove(e)} };
			ls["pointerdown"] = {t:this.canvas, f:function(e) { _this._handleMouseDown(e)} };
```
to enableDOMEvents seems to help, if not solve the issue. Still investigating.

**Comment by amihanya** [comment]
+1

@masandoval were to add that code?

**Comment by amihanya** [comment]
Dan Zen from zim add that: https://zimjs.com/explore/drag2.html
that better becuse the drag work. but the mousemove lose after one move and dont stay.
please help 👍

**Comment by danzen** [comment]
Yes - I added the three lines below in the enableDOMElements of Stage.  Ami reported a slight improvement but the pressmove in the https://zimjs.com/explore/drag2.html example only runs a couple of times then stops running - no error in the console.
ls["mouseup"] = {t:t, f:function(e) { _this._handleMouseUp(e)} };
ls["mousemove"] = {t:t, f:function(e) { _this._handleMouseMove(e)} };
ls["dblclick"] = {t:this.canvas, f:function(e) { _this._handleDoubleClick(e)} };
ls["mousedown"] = {t:this.canvas, f:function(e) { _this._handleMouseDown(e)} };
// masandoval from https://github.com/CreateJS/EaselJS/issues/997
ls["pointerup"] = {t:t, f:function(e) { _this._handleMouseUp(e)} };
ls["pointermove"] = {t:t, f:function(e) { _this._handleMouseMove(e)} };
ls["pointerdown"] = {t:this.canvas, f:function(e) { _this._handleMouseDown(e)} };

**Comment by masandoval** [comment]
By using pointer events instead of mouse events I was able to restore functionality in the app I'm working on, but Firefox slows down considerably when using the pointer events (even when mouse events are not added). Currently I'm using userAgent to determine if the Chrome version is 70+ to apply the changed event types, and using what already works (mouse events) in all other cases. Definitely not an ideal solution.

```
p.enableDOMEvents = function(enable) {
		if (enable == null) { enable = true; }
		var n, o, ls = this._eventListeners;
		if (!enable && ls) {
			for (n in ls) {
				o = ls[n];
				o.t.removeEventListener(n, o.f, false);
			}
			this._eventListeners = null;
		} else if (enable && !ls && this.canvas) {
			var t = window.addEventListener ? window : document;
			var _this = this;
			ls = this._eventListeners = {};

			var raw = navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);
			var usePointerEvents = (raw ? parseInt(raw[2], 10) : false) >= 70;
			if (usePointerEvents) {
				ls["pointerup"] = {t:t, f:function(e) { _this._handleMouseUp(e)} };
				ls["pointermove"] = {t:t, f:function(e) { _this._handleMouseMove(e)} };
				ls["dblclick"] = {t:this.canvas, f:function(e) { _this._handleDoubleClick(e)} };
				ls["pointerdown"] = {t:this.canvas, f:function(e) { _this._handleMouseDown(e)} };
			} else {
				ls["mouseup"] = {t:t, f:function(e) { _this._handleMouseUp(e)} };
				ls["mousemove"] = {t:t, f:function(e) { _this._handleMouseMove(e)} };
				ls["dblclick"] = {t:this.canvas, f:function(e) { _this._handleDoubleClick(e)} };
				ls["mousedown"] = {t:this.canvas, f:function(e) { _this._handleMouseDown(e)} };
			}

			for (n in ls) {
				o = ls[n];
				o.t.addEventListener(n, o.f, false);
			}
		}
	};
```

**Comment by masandoval** [comment]
Changing chrome://flags/#touch-events to "Automatic" from "Disabled" restores functionality.
Appears related to this change: https://www.chromestatus.com/feature/4764225348042752

**Comment by masandoval** [comment]
The core issue is that Touch.js uses 'ontouchstart' to determine if touch is supported; this is no longer possible in Chrome with the changes in Chrome 70.

I've added some Chrome-specific support to Touch enabling and disabling, and so far everything seems to be fixed for my implementation. This will be my first attempt at creating a pull request, but I'll try to share my changes so you can take a look and try them out yourselves.

**Comment by masandoval** [comment]
After comparing my changes to current master, I noticed my changes to Touch.js weren't fully up-to-date. If I use the master branch and point to easeljs-NEXT, my issue is resolved. This seems like a feasible work-around until 1.0.3 is released.

**Comment by amihanya** [comment]
thanks! we wait yo 1.0.3 :)

**Comment by danzen** [comment]
Hi @masandoval... can you please describe what changes you did to make pressmove work on newer laptop touchscreens - I have had reports of MS Surface and the new HP laptop touch screens in both Safari and Chrome not working for pressmove.  The code that you added above (https://github.com/CreateJS/EaselJS/issues/997#issuecomment-437964801) we tried and it still does not work properly - it sort of stutters along.  I am testing with this page: https://zimjs.com/explore/drag2.html.  Or @lannymcnie if more than what was posted went into the NEXT version, could you point to where I can find that - I checked NEXT but did not see it - maybe I am looking in the wrong place or for the wrong thing.  Thanks.  I would like to apply a patch if possible to some older libraries to make existing content work.  Thanks.

**Comment by masandoval** [comment]
@danzen I didn't end up applying any changes to CreateJS to fix my issue, other than updating to use EaselJS/master instead of v1.0.2.

My hunch is the changes to fix IE/Edge Pointer events also managed to catch this case, although I haven't done extensive testing to determine which specific commits between v1.0.2 and current master fix the issue. I might look at the following changes to Touch.js:

- bb3398938e3fed3fa405e245027a6f380e5ffc42
- 8fd7119a5a3b9ce16e920663c4f6c76459f65ea9
- 848dcbf765abd00234569fd348e4402e329f5708

**Comment by danzen** [comment]
Thanks @masandoval I have implemented the Touch.js locally here and updated the test file at https://zimjs.com/explore/drag.html - I don't have a chromeBook, etc. if you could spare a moment and let me know if it works - that would be great.  Thanks.  We should see the numbers go up when dragging on the rectangle.  And the circle should drag.  The triangle is capturing mousedown location.

**Comment by danzen** [comment]
@masandoval - oops - good news, I hope.  I had not properly updated the file on the server.  I don't want to debug any further here but perhaps you could try just one last time and let me know.  The rectangle should show changing numbers as you drag on it.  The circle should drag.  The triangle does not drag - just reports the mousedown position.  Thanks!

**Comment by danzen** [comment]
Just had it tested and it works well.  Yay.  So, just confirming - https://github.com/CreateJS/EaselJS/issues/997#issuecomment-440719888 works!

**Comment by lannymcnie** [comment]
Just to confirm, is this solved with the latest updates to the touch class, or does it require additional patches? Happy to accept a PR for the latter.

**Comment by danzen** [comment]
@lannymcnie I think it is solved with the latest updates to the touch class.  At least I have one confirmation that it is now working - I have two other test requests out there and will report back if anything does not work.

**Comment by jpwalters1** [comment]
Wow, until I saw some screenshots of this actually happening out in the field on touchscreens, I was thinking it was a hardware or setting issue.

**Comment by danzen** [comment]
> 
> 
> @lannymcnie I think it is solved with the latest updates to the touch class. At least I have one confirmation that it is now working - I have two other test requests out there and will report back if anything does not work.

The two other tests also reported that the issue was solved.  I think they were running windows touch screens though.  I will see if @Johnafriedman will test my URL on the mac...

**Comment by danzen** [comment]
Hey @lannymcnie hate to bring this up again - but maybe it is not solved - apparently an enable touch setting defaults to false on Chrome and users have to turn it on before pressmove works.  A fellow called Ferudun reports that other libraries pixijs, konva, fabricjs are working without the setting on.  I am not sure what is going on but he may post here....

**Comment by lannymcnie** [comment]
@danzen Yeah, could be like unlocking audio context :(

**Comment by gonulbuya** [comment]
With google chrome 70 version touch enable apisini disabel made. No problem with other html5 canvas libraries. Just createjs touch does not work. Have you done anything to solve this problem lately?

**Comment by gonulbuya** [comment]
![image](https://user-images.githubusercontent.com/48065985/53514237-57afd980-3ad8-11e9-80de-84f416459c34.png)

**Comment by jpwalters1** [comment]
My solution was to replace the touch.js inside our current version of the create js library with the touch.js from the latest code branch where this seems to be resolved.

**Comment by gonulbuya** [comment]
can I find the most recent touch.js code resolved? Can you send it?

**Comment by jpwalters1** [comment]
https://github.com/CreateJS/EaselJS/blob/master/lib/easeljs-NEXT.js

**Comment by gonulbuya** [comment]
my problem is solved. Thank you for your help.
well that's solved. I don't like other canvas libraries.

**Comment by gonulbuya** [comment]
problem solved. But there is a nuisance on the smart board with the window: the click action on the page placed in the iframe is troubling. Sometimes it doesn't click at all, sometimes it does double click. If the page is not in the iframe, there are no problems.

**Comment by gonulbuya** [comment]
problem solved. But on the Windows installed smart board, there is a nuisance: the click action on the page placed in the iframe is troublesome. Sometimes it doesn't click at all, sometimes it does double click. If the page is not in the iframe, there are no problems.

**Comment by gonulbuya** [comment]
![20190305_155953](https://user-images.githubusercontent.com/48065985/53830577-d2bf3700-3f93-11e9-8b68-d81027ac987f.jpg)

**Comment by gonulbuya** [comment]
![20190305_160018](https://user-images.githubusercontent.com/48065985/53830617-f1253280-3f93-11e9-9d07-31b274425481.jpg)

**Comment by gonulbuya** [comment]
There is a "click" problem when the html page is in the iframe. No problem when there is no.

**Comment by gonulbuya** [comment]
[touchTest.zip](https://github.com/CreateJS/EaselJS/files/2938086/touchTest.zip)

**Comment by danzen** [comment]
I created a test page for the iFrame issue to https://zimjs.com/test/iframe.html and @gonulbuya reports that this too is not working properly on the SMART board.  It works on my touch screen.  You press the circle and it animates but it is not working on mousedown or click on SMART Board.

**Comment by gonulbuya** [comment]
I found the cause of the problem. Both on mouse and touch windows computers when the page was in the iframe, sometimes it was double-clicked. This happens because the cursor is a pointer.

	p._setEnabled = function(value) {
		if (value == this._enabled) { return; }
		var o = this.target;
		this._enabled = value;
		if (value) {
			o.cursor = "pointer";  /// >>>>>> " changed"
			o.addEventListener("rollover", this);
			o.addEventListener("rollout", this);
			o.addEventListener("mousedown", this);
			o.addEventListener("pressup", this);
			if (o._reset) { o.__reset = o._reset; o._reset = this._reset;}
		} else {
			o.cursor = null;
			o.removeEventListener("rollover", this);
			o.removeEventListener("rollout", this);
			o.removeEventListener("mousedown", this);
			o.removeEventListener("pressup", this);
			if (o.__reset) { o._reset = o.__reset; delete(o.__reset); }
		}
	};

**Comment by roughee** [comment]
@gonulbuya I am not sure why the cursor had a change for you, because it is a css value of the cursor.

I found that if I updated my Touch.js that it would then trigger both pointer events binded in Touch._IE_enable function and mouse events in p.enableDOMEvents function. (inside an iframe)

Because when you touch touchscreen on desktop it will emit Pointer events and mouse events. (with touch api disabled by default on chrome v72)
You can see in chrome console by `monitorEvents(document.body)`

So I updated my Touch.js and added a similar fix from comments above in p.enableDOMEvents.

```
p.enableDOMEvents = function(enable) {
	if (enable == null) { enable = true; }
	var n, o, ls = this._eventListeners;
	if (!enable && ls) {
		for (n in ls) {
			o = ls[n];
			o.t.removeEventListener(n, o.f, false);
		}
		this._eventListeners = null;
	} else if (enable && !ls && this.canvas) {
		var t = window.addEventListener ? window : document;
		var _this = this;
		ls = this._eventListeners = {};

		if ( (window.MSPointerEvent && window.navigator.msMaxTouchPoints > 0) 
			  || (window.PointerEvent && window.navigator.maxTouchPoints > 0) ) {
                       
                        //pointer events mapped in Touch.js

			ls["dblclick"] = {t:this.canvas, f:function(e) { _this._handleDoubleClick(e)} };
		} else {
			ls["mouseup"] = {t:t, f:function(e) { _this._handleMouseUp(e)} };
			ls["mousemove"] = {t:t, f:function(e) { _this._handleMouseMove(e)} };
			ls["dblclick"] = {t:this.canvas, f:function(e) { _this._handleDoubleClick(e)} };
			ls["mousedown"] = {t:this.canvas, f:function(e) { _this._handleMouseDown(e)} };
		}

		for (n in ls) {
			o = ls[n];
			o.t.addEventListener(n, o.f, false);
		}
	}
};
```

You can map all pointer events in p.enableDOMEvents but I needed canvas.style.touchAction = "none"; from Touch.js, because otherwise when you drag and drop things windows/chrome tries to navigate you away with a back arrow.

**Comment by gonulbuya** [comment]
Yes only the annoyance is happening in the chrome browser. Again the problem is happening on the devices used in the mouse and touch together. Also iframe is going on used pages. The mouse is first used and then the double click is used. To avoid this, I wrote the following code:

	Touch._IE_handleEvent = function(stage, e) {
		if (!stage) { return; }
		if (stage.__touch.preventDefault) { e.preventDefault && e.preventDefault(); }
		var type = e.type;
		var id = e.pointerId;
		var ids = stage.__touch.activeIDs;

		if (type === "MSPointerDown" || type === "pointerdown") {
			if (e.srcElement != stage.canvas) { return; }
			ids[id] = true;
			this._handleStart(stage, id, e, e.pageX, e.pageY);
            
           //////The reason for adding this is to determine the pointer type////
            switch(e.pointerType) {
              case 'mouse':
           
             stage.enableDOMEvents(true);
          
                break;
              case 'touch':
              
               stage.enableDOMEvents(false);
             
                break;
              case 'pen':
               
                break;
              default:
              
                break;
            }  
            
           //////////////////////////////////////////// 
            
		} else if (ids[id]) { // it's an id we're watching
			if (type === "MSPointerMove" || type === "pointermove") {
				this._handleMove(stage, id, e, e.pageX, e.pageY);
			} else if (type === "MSPointerUp" || type === "MSPointerCancel"
					|| type === "pointerup" || type === "pointercancel") {
				delete(ids[id]);
				this._handleEnd(stage, id, e);
			}
		}
	};

**Comment by gonulbuya** [comment]
if cursor = "pointer", the display is flashing. I solved her this way:

p._setEnabled = function(value) {
	if (value == this._enabled) { return; }
	var o = this.target;
	this._enabled = value;
	if (value) {
		o.cursor = "pointer";  /// >>>>>> " changed"
		o.addEventListener("rollover", this);
		o.addEventListener("rollout", this);
		o.addEventListener("mousedown", this);
		o.addEventListener("pressup", this);
		if (o._reset) { o.__reset = o._reset; o._reset = this._reset;}
	} else {
		o.cursor = null;
		o.removeEventListener("rollover", this);
		o.removeEventListener("rollout", this);
		o.removeEventListener("mousedown", this);
		o.removeEventListener("pressup", this);
		if (o.__reset) { o._reset = o.__reset; delete(o.__reset); }
	}
};

Kesinlikle sorunu çözdü.

**Comment by lannymcnie** [comment]
If anyone is interested, I rolled the latest touch changes into a 0.8.3 branch
https://github.com/CreateJS/EaselJS/tree/0.8.3-TOUCHFIX

**Comment by gonulbuya** [comment]
> Herhangi biri ilgileniyorsa, son dokunma değişikliklerini 0.8.3 dalına aldım. 
> [Https://github.com/CreateJS/EaselJS/tree/0.8.3-TOUCHFIX](https://github.com/CreateJS/EaselJS/tree/0.8.3-TOUCHFIX)

When I use the touch.js you shared above, the windows are still having problems with the touch screens. The question acts as a double click when using the iframe. In addition, touching with the touch of the screen is again illumination. The solution I found myself

Touch._IE_handleEvent = function (stage, e) {
if (! stage) {return; }
if (stage .__ touch.preventDefault) {e.preventDefault && e.preventDefault (); }
var type = e.type;
var id = e.pointerId;
var ids = stage .__ touch.activeIDs;

if (type === "MSPointerDown" || type === "pointerdown") {
if (e.srcElement! = stage.canvas) {return; }
ids [id] = true;
this._handleStart (stage, id, e, e.pageX, e.pageY);
        
       ////// The reason for this pointer
        switch (e.pointerType) {
          case 'mouse':
       
         stage.enabledomevents (true);
      
            break;
          case 'touch':
          
           stage.enabledomevents (false);
         
            break;
          case 'pen':
           
            break;
          default:
          
            break;
        }
        
       ////////////////////////////////////////////
        
{id = [id] [id]
if (type === "MSPointerMove" || type === "pointermove") {
this._handleMove (stage, id, e, e.pageX, e.pageY);
} else if (type === "MSPointerUp" || type === "MSPointerCancel"
|| type === "pointerup" || type === "pointercancel") {
delete (ids [id]);
this._handleEnd (stage, id, e);
}
}
};


and
if cursor = "pointer", the display is flashing. I solved her this way:

p._setEnabled = function (value) {
if (value == this._enabled) {return; }
var = this.target;
this._enabled = value;
if (value) {
o.cursor = "pointer"; /// >>>>>> "changed" "grab"
o.addEventListener ("rollover", this);
o.addEventListener ("rollout", this);
o.addEventListener ("mousedown", this);
o.addEventListener ("pressup", this);
if (o._reset) {o .__ reset = o._reset; o._reset = this._reset;
} else {
o.cursor = null;
o.removeEventListener ("rollover", this);
o.removeEventListener ("rollout", this);
o.removeEventListener ("mousedown", this);
o.removeEventListener ("pressup", this);
if (o .__ reset) {o._reset = o .__ reset; delete (reset .__ o); }
}
};

**Comment by gonulbuya** [comment]
the mouse pointer "pointer" cannot be used in such a solution.

**Comment by owendwyer** [comment]
> If anyone is interested, I rolled the latest touch changes into a 0.8.3 branch
> https://github.com/CreateJS/EaselJS/tree/0.8.3-TOUCHFIX

Is there a branch of the combined library with the touchfix?

I couldn't find anything recent on Github.  So I've started using a copy of createjs.1.1 that I grabbed from one of the test pages DanZen posted above.

It was linked on this page
https://zimjs.com/test/iframe.html
The actual file
https://d309knd7es5f10.cloudfront.net/createjs_1.1_min.js 

I don't know anything about this version, other than it seems to work.

**Comment by danzen** [comment]
@owendwyer here is the non minified file https://zimjs.com/live/createjs_1.1.js and here is the file before the touch changes https://zimjs.com/live/createjs_1.1_preTouch.js.  Since this was labeled by us as 1.1 even before the touch... I think there might be a little something in there that we modified.  But it would not be much... perhaps it we removed a warning about some stage setting or something like.  You can do a file comparison with a combined file from CreateJS if you want.

**Comment by owendwyer** [comment]
Many thanks!

**Comment by owendwyer** [comment]
Hi,

in the touch.js class - https://github.com/CreateJS/EaselJS/blob/0.8.3-TOUCHFIX/src/easeljs/ui/Touch.js
this function causes an error when called in Firefox

`Touch.disable = function(stage) {
		if (!stage) { return; }
		if ('ontouchstart' in window) { Touch._IOS_disable(stage); }
		else if (window.PointerEvent || window.MSPointerEvent) { Touch._IE_disable(stage); }
		
		delete stage.__touch;
	};`

It causes an error (in Firefox) because Touch._IE_disable(stage) is called and tries to use the variable stage.__touch.   
However, the variable stage.__touch is undefined due to Touch.isSupported returning false earlier.

A fix would be to change the function to 

`Touch.disable = function(stage) {
		if (!stage.__touch) { return; }
		if ('ontouchstart' in window) { Touch._IOS_disable(stage); }
		else if (window.PointerEvent || window.MSPointerEvent) { Touch._IE_disable(stage); }
		
		delete stage.__touch;
	};`

Looking at https://github.com/CreateJS/EaselJS/blob/2.0/src/ui/Touch.js I think the problem might also exist there too.

**Comment by danzen** [comment]
hahaha @owendwyer just came in to mention you might want (!stage||!stage.__touch) and you had changed it already ;-).  We updated our ZIM version - but you guys will be wanting to use an updated CreateJS version of course.

**Comment by owendwyer** [comment]
Also, I'm adding a check for window.TouchEvent in isSupported.  Without this, I can't get Firefox to work with touch.

`Touch.isSupported = function() {
	return !!(('ontouchstart' in window) // iOS & Android
		|| window.TouchEvent 
		|| (window.MSPointerEvent && window.navigator.msMaxTouchPoints > 0) // IE10
		|| (window.PointerEvent && window.navigator.maxTouchPoints > 0)); // IE11+
};`

**Comment by matmaker9** [comment]
I can confirm, that @owendwyer 's correction in isSupported function (adding window.touchEvent check) resolved problem in Firefox with touch on interactive whiteboards, used in schools (our clients). Without this correction touch didn't work in Firefox.

**Comment by danzen** [comment]
That's great!  I had turned dom.w3c_touch_events.legacy_apis.enabled to true to get it to work which was not an optimal solution.  https://github.com/CreateJS/EaselJS/issues/1035.  Will point that issue here...

**Comment by danzen** [comment]
@owendwyer and @matmaker9 - I am getting a double event happening with the new code on my HP TouchScreen monitor.  Here is an example https://zimjs.com/components/ - dragging the slider and dial works (yay) but if you press the button it opens and closes the pane.  RadioButtons select and deselect, etc.  Here is the old code where the dragging does not work https://zimjs.com/components/index2.html but the press on the button goes once as expected.

I notice in the code in the Touch.enable function below that there is a comment:
// note that in the future we may need to disable the standard mouse event model before adding
// these to prevent duplicate calls. It doesn't seem to be an issue with iOS devices though.  
Any thoughts @gskinner @lannymcnie or others...

Note... with the Firefox about:config dom.w3c_touch_events.legacy_apis.enabled set to true I get the best of both worlds - dragging and single touch action with or without the new code.

**Comment by owendwyer** [comment]
Yes, I'm seeing the same thing.  For Firefox on Windows, a touch fires twice.

Changing the singleTouch or allowDefault parameters in the Touch.enable function doesn't seem to make any difference.

I don't know if this is going to get resolved.  My solution will be to only call Touch.enable when necessary for dragging and then manually catch and prevent 2nd touches.

**Comment by owendwyer** [comment]
I looked into this a little more.  Seems the difference between Chrome and Firefox is that the _handlePointerUp function is called once in Chrome and twice in Firefox, hence the double tap.

Prior to Touch.enable being called, the mouseup and mousedown events are used and mouseup leads to _handlePointerUp.  This is the same for both FF and Chrome.

After Touch.enable has been called, pointer events are used and pointerup/pointerevent leads to _handlePointerUp.  The difference is that in FF the mouseup event is still active and still leads to _handlePointerUp, so it is called twice - once by pointerup and once by mouseup.  In Chrome you just get pointerevent and no mouseup.

What is really strange is that this only happens for touch interactions.  When you use the mouse, you get pointerup, but if you touch the screen you get pointerup and mouseup.

I looked at calling stage.enableDOMEvents(false), thinking that it might be what was being alluded to in the comments, but it seems to create other problems.  

It might  be possible to add a line in this function 
`	p._handleMouseUp = function(e) {
		this._handlePointerUp(-1, e, false);
	};`
So that _handlePointerUp only gets called if touch hasn't been enabled.

**Comment by danzen** [comment]
Okay... I think I see what is going on.  Recently, Firefox changed to use Touch as the event for everything including the mouse.  The legacy only used mousedown and mouseup for mouse.  So the current CreateJS is firing for touch and mouse.  Now... in firefox and chrome you can just comment out these lines: 

```
// ls["mouseup"] = {t:t, f:function(e) { _this._handleMouseUp(e)} };
ls["mousemove"] = {t:t, f:function(e) { _this._handleMouseMove(e)} };
ls["dblclick"] = {t:this.canvas, f:function(e) { _this._handleDoubleClick(e)} };
// ls["mousedown"] = {t:this.canvas, f:function(e) { _this._handleMouseDown(e)} };
```
and it works fine.  Unfortunately, if you have the legacy setting on (dom.w3c_touch_events.legacy_apis.enabled=true) or are on an old browser, then mouse interaction will not work if you comment out those lines.

Before commenting out the lines above, I did add a test to see if there was already a call to the _handlePointerDown:

```
var pointerDownCheck = false;
	p._handlePointerDown = function(id, e, pageX, pageY, owner) {
        if (pointerDownCheck) return;
        pointerDownCheck = true;
        setTimeout(function(){
            pointerDownCheck = false;
        }, 200);
```

And it worked but I had to up the time to 200 ms to make sure - it would not work at 50ms for instance.  There might be another way to handle this = like don't count a down unless an up has happened.  I find stopping the double mousedown works better than stopping the double mouseup.  So... leaving this here to mull.  There may be a way to test if firefox is using the legacy api in which case we should not comment out the two lines - otherwise... commenting out the two lines and more testing on mobile, safari, etc. could be done.

**Comment by owendwyer** [comment]
Yes, that prevents the double tap.

I think a good wider solution would be to remove the listeners when Touch.enable is called.  Specifically, after it has checked that Touch is supported.  That way older browsers can still use the mouse events.

A record of the listeners is stored in stage._eventListeners so I think it should be straightforward to remove them.

Also, I think mousemove might still be needed for mouse over and other events, so perhaps just remove the mouseup and mousedown listeners.

**Comment by dijitaletkinlikler** [comment]
Touch._IE_handleEvent = function (stage, e) {
if (! stage) {return; }
if (stage .__ touch.preventDefault) {e.preventDefault && e.preventDefault (); }
var type = e.type;
var id = e.pointerId;
var ids = stage .__ touch.activeIDs;

if (type === "MSPointerDown" || type === "pointerdown") {
if (e.srcElement! = stage.canvas) {return; }
ids [id] = true;
this._handleStart (stage, id, e, e.pageX, e.pageY);
            
           ////// The reason for adding this is to determine the pointer type ////
            switch (e.pointerType) {
              case 'mouse':
           
             stage.enabledomevents (true);
            
          
                break;
              case 'touch':
              
               stage.enabledomevents (false);
             
                break;
              case 'pen':
               
                break;
              default:
              
                break;
            }
            
            
            
} else if (ids [id]) {// it's an id we're watching
if (type === "MSPointerMove" || type === "pointermove") {
this._handleMove (stage, id, e, e.pageX, e.pageY);
} else if (type === "MSPointerUp" || type === "MSPointerCancel"
|| type === "pointerup" || type === "pointercancel") {
delete (ids [id]);
this._handleEnd (stage, id, e);
}
}
};


This is the original version:
Touch._IE_handleEvent = function (stage, e) {
if (! stage) {return; }
if (stage .__ touch.preventDefault) {e.preventDefault && e.preventDefault (); }
var type = e.type;
var id = e.pointerId;
var ids = stage .__ touch.activeIDs;

if (type === "MSPointerDown" || type === "pointerdown") {
if (e.srcElement! = stage.canvas) {return; }
ids [id] = true;
this._handleStart (stage, id, e, e.pageX, e.pageY);

} else if (ids [id]) {// it's an id we're watching
if (type === "MSPointerMove" || type === "pointermove") {
this._handleMove (stage, id, e, e.pageX, e.pageY);
} else if (type === "MSPointerUp" || type === "MSPointerCancel"
|| type === "pointerup" || type === "pointercancel") {
delete (ids [id]);
this._handleEnd (stage, id, e);
}
}
};

I'm checking if there is touch with pointer type. If there is touch, stage.enableDOMEvents (false); I'm setting. So I avoid double-touching.

**Comment by dijitaletkinlikler** [comment]
createjs touch newest running version

[createjs.zip](https://github.com/CreateJS/EaselJS/files/3763135/createjs.zip)

**Comment by owendwyer** [comment]
That seems like it should work; however, you're add/removing listeners on every down event.  For every tap or click the stage.enableDOMEvents function is being called. You should just call it once.  

It is not just that it is messy; things like this are what leads to memory leaks.  Every time there is a pointerType of mouse, you're adding listeners.  I don't know how that would be handled exactly, but I think it's a bad idea.

I think a better solution would be to call stage.enableDOMEvents in the Touch.enable function.  Something like this

`		Touch.enable = function(stage, singleTouch, allowDefault) {
			console.log('supp',Touch.isSupported())
			if (!stage || !stage.canvas || !Touch.isSupported()) { return false; }
			//if (!stage || !stage.canvas || !Touch.isSupported()) { return false; }
			if (stage.__touch) { return true; }
			// inject required properties on stage:
			stage.__touch = {pointers:{}, multitouch:!singleTouch, preventDefault:!allowDefault, count:0};

			// note that in the future we may need to disable the standard mouse event model before adding
			// these to prevent duplicate calls. It doesn't seem to be an issue with iOS devices though.
			stage.enableDOMEvents(false);
			if ('ontouchstart' in window) { Touch._IOS_enable(stage); }
			else if (window.PointerEvent || window.MSPointerEvent) { Touch._IE_enable(stage); }
			return true;
		};`

Note I haven't tested this.

**Comment by dijitaletkinlikler** [comment]
I was having trouble with the chrome browser on the smart board when I first use the mouse and then touch it. I developed such a solution. A good solution to this I think I have not seen so far. Hopefully a good one will be found soon.

**Comment by danzen** [comment]
Excellent, I was just checking this earlier and planned to fixing this evening.  And came in now and you have a possible solution.  It is close - unfortunately, if I have dom.w3c_touch_events.legacy_apis.enabled set to true on Firefox in the about:config then it does not work with normal mouse presses.  BTW - the existing CreateJS does work if legacy apis is true.  So... just going to hunt to see if we can detect with JavaScript if legacy apis is set in Firefox.

**Comment by danzen** [comment]
Excellent, I was just checking this earlier and planned to fixing this evening.  And came in now and you have a possible solution.  It is close - unfortunately, if I have dom.w3c_touch_events.legacy_apis.enabled set to true on Firefox in the about:config then it does not work with normal mouse presses.  BTW - the existing CreateJS does work if legacy apis is true.  After hunting around I can't see how to detect with JavaScript if legacy apis is set in Firefox.  Is there something else we might be able to use to figure it out?

**Comment by danzen** [comment]
Here is what I have done to fix the Firefox touch issue on desktop:

1. Used the @owendwyer fix to get touch working on Firefox now that the original CreateJS touch check is broken because Firefox removed certain touch events on desktop so it does not appear as a mobile device https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#Browser_compatibility.

```
Touch.isSupported = function() {
    return !!(
        ('ontouchstart' in window) // iOS & Android

        // https://github.com/owendwyer addition June 10 2019
        || window.TouchEvent

        || (window.MSPointerEvent && window.navigator.msMaxTouchPoints > 0) // IE10
        || (window.PointerEvent && window.navigator.maxTouchPoints > 0)
    ); // IE11+
};
```
2. Unfortunately, this leads to two events on touch down in Firefox - one for the DOM mouse event and one for the touch event (and two up events as well).  So for current Firefox we need to remove the DOM mousedown and mouseup events.  BUT for legacy Firefox (and Safari on Desktop) these are needed.  Chrome works either way.  So... removed the two DOM events only for current Firefox as follows in the p.enableDOMEvents:

```
// Dan Zen change October 23 2019 for Desktop Firefox Touch Screen Issues
if (!createjs.BrowserDetect.isFirefox || 'ontouchstart' in window) { // allows legacy Firefox
    ls["mousedown"] = {t:this.canvas, f:function(e) { _this._handleMouseDown(e)} };
    ls["mouseup"] = {t:t, f:function(e) { _this._handleMouseUp(e)} };
}

ls["mousemove"] = {t:t, f:function(e) { _this._handleMouseMove(e)} };
ls["dblclick"] = {t:this.canvas, f:function(e) { _this._handleDoubleClick(e)} };
```

Please let me know if this works well for you.  Tested on PC (with touch screen and mouse) Firefox, Firefox with legacy Touch APIs, Chrome, Edge, Mac (mouse only) Chrome and Safari, mobile Android Chrome and iOS Chrome and Safari.  

Here is my test page: https://zimjs.com/explore/touch.html and a link to the version of non-minified version of CreateJS https://zimjs.com/cdn/1.2.2/createjs.js

**Comment by danzen** [comment]
Darn - we had issues on some Firefox browsers - I think it worked when there was a Touch screen attached but otherwise not.  So we did a rethink along the lines of what we were trying before and I think we have it.  Anyone is welcome to confirm at our test page https://zimjs.com/explore/touch.html make sure to clear cache.  Here is what we added (ignore part 2 of my previous post):

// 1. outside Touch class
var pointerCheck = false; 

// 2. Then inside iOS and IE enable functions do the same thing in each:
// Dan Zen adjust October 28 2019 to stop double events on Firefox touch screens
// Note the f2 below rather than f
// both the mousedown and mouseup events seem to fire after the pointerup - ?
// see also DOMEvents with associated Dan Zen change
var f2 = stage.__touch.f2 = function(e) {
    pointerCheck = true;
    clearTimeout(touchUpTimeout);
    touchUpTimeout = setTimeout(function() {
        pointerCheck = false;
    }, 20);
    f(e); // call the original
};

// 3. then in the various touchend calls (both adding and removing) change it to f2 
canvas.addEventListener("touchend", f2, false); // Dan Zen change

// 4. then in the enableDOMEvents function:
// added pointerCheck so these do not fire if pointer events have fired
ls["mousedown"] = {t:this.canvas, f:function(e) {if (!pointerCheck) _this._handleMouseDown(e)} };
ls["mouseup"] = {t:t, f:function(e) {if (!pointerCheck) _this._handleMouseUp(e)} };

So that has been implemented in https://zimjs.org/cdn/1.2.3/createjs.js and then here is the minified file https://zimjs.org/cdn/1.2.3/createjs_min.js - you guys can test it and do what you need to do.

**Comment by owendwyer** [comment]
That works for me for Firefox and Chromium on Ubuntu.  This solution is good as it keeps the mousemove events too so you still get mouseover effects.

Putting the pointerCheck inside the function is quite nifty too.

I'd be tempted to get rid of the timeouts though.  And instead just use pointerCheck as an on off switch for those 2 events.  Maybe get rid of points 2 and 3 altogether and just have one line with pointerCheck set to true when Touch.enable is called.  Once you've added the listeners for the pointer events, I think the mouseup and mousedown events are redundant anyway, so why not just leave them off?  I guess there might be some legacy issues.

**Comment by dijitaletkinlikler** [comment]
Hello there. createjs.1.2.3 works fine in both chrome and firefox. Double click no longer exists. This solution was a terrific thing. I was sure you would solve this problem. Thank you very much. But I told you when I was writing with you on facebook. flashes when cursor = "pointer". This only happens in chrome. Could it be because of my codes? Or could it be from chrome?

**Comment by danzen** [comment]
Sorry for the delay on this - I could not figure it out earlier.  But coming back to it... I decided to test just regular HTML with cursor:pointer and found that Chrome automatically highlights the tag with the cursor setting!  So it was highlighting the whole canvas.  Once I realized it was in general - it was pretty easy to find the solution.  I have added this line to our ZIM version of CreateJS:

```
Touch._IE_enable = function(stage) {
	var canvas = stage.canvas;
        var f = stage.__touch.f = function(e) {Touch._IE_handleEvent(stage,e); };

         // Dan Zen added this to stop flashing in Chrome Dec 30, 2019
         // thanks Ferudun Vural for report
         canvas.style["-webkit-tap-highlight-color"] = "transparent";
```

**Comment by dijitaletkinlikler** [comment]
thank you so much. I've tried it all. It works smoothly.

**Comment by IestynBJones** [comment]
I implemented your new Touch.js code and this fixed touch issues on all the browsers our schools use. Thank you. But it has introduced a problem with keyboard events. When a createjs resource is loaded into an iFrame touch/mouse works fine but it kills keyboard events in IE and Edge (the zimjs.org/cdn/1.2.3/createjs.js fix breaks keyboard in Chrome too). If the resource isn't in an iFrame it works in all browsers. You can see an example of the problem here where this educational resource (in an iFrame) can be used with both on screen buttons or the keyboard arrow keys:

https://www.echalk.co.uk/info/ItJustWorks/resources/tetrisTable/tetrisTable.html

Any ideas how to fix this?

**Comment by dijitaletkinlikler** [comment]
[createjs.zip](https://github.com/CreateJS/EaselJS/files/4186285/createjs.zip)
Bunu deneyip sonucu bildirir misiniz?

**Comment by dijitaletkinlikler** [comment]
[createjs.zip](https://github.com/CreateJS/EaselJS/files/4186292/createjs.zip)
Can you try this and report the result?

**Comment by dijitaletkinlikler** [comment]
> I implemented your new Touch.js code and this fixed touch issues on all the browsers our schools use. Thank you. But it has introduced a problem with keyboard events. When a createjs resource is loaded into an iFrame touch/mouse works fine but it kills keyboard events in IE and Edge (the zimjs.org/cdn/1.2.3/createjs.js fix breaks keyboard in Chrome too). If the resource isn't in an iFrame it works in all browsers. You can see an example of the problem here where this educational resource (in an iFrame) can be used with both on screen buttons or the keyboard arrow keys:
> 
> https://www.echalk.co.uk/info/ItJustWorks/resources/tetrisTable/tetrisTable.html
> 
> Any ideas how to fix this?
> 
> I should add I'm using the Touch.js from here: https://github.com/CreateJS/EaselJS/tree/0.8.3-TOUCHFIX which works in Chrome but not Edge and IE on Windows desktop machines. The zim touch fix breaks the keyboard in all browsers when the resource is in an iFrame.

[createjs.zip](https://github.com/CreateJS/EaselJS/files/4186295/createjs.zip)
Can you try this and report the result?

**Comment by IestynBJones** [comment]
> [createjs.zip](https://github.com/CreateJS/EaselJS/files/4186292/createjs.zip)
> Can you try this and report the result?

Thank you for your help. I quickly tried the createjs library you supplied. It didn't fix the resource in an iFrame keyboard issue in IE and Edge. The only difference I can see is that I also see the issue in Chrome.

The issue I'm facing is that I'm trying to fix legacy resources which were built on easeljs-0.7.1_14.5.30.min.js. I was able to fix the touch issue by appending your new Touch.js class to this file (overwriting the old one). 
When I use the new createJS library certain features in the resources break (due to deprecated functions I expect). For this reason do you have just the modified Touch.js code so I can append that to the old easel library I'm using.

**Comment by dijitaletkinlikler** [comment]
> > [createjs.zip](https://github.com/CreateJS/EaselJS/files/4186292/createjs.zip)
> > Can you try this and report the result?
> 
> Thank you for your help. I quickly tried the createjs library you supplied. It didn't fix the 'resource in an iFrame keyboard issue' in IE and Edge. The only difference I can see is the issue now appears in Chrome too.
> 
> The problem I'm facing is that I'm trying to fix legacy resources which were built on easeljs-0.7.1_14.5.30.min.js. I was able to fix the touch issue by appending your new Touch.js class to this file (overwriting the old Touch class).
> When I use the new createJS library certain features in the resources break (due to deprecated functions I expect). For this reason do you have just the modified Touch.js code so I can append that to the old easel library I'm using.

if you just add the touch js code. this time, double click problem occurs in chrome and firefot.

**Comment by dijitaletkinlikler** [comment]
> > [createjs.zip](https://github.com/CreateJS/EaselJS/files/4186292/createjs.zip)
> > Can you try this and report the result?
> 
> Thank you for your help. I quickly tried the createjs library you supplied. It didn't fix the 'resource in an iFrame keyboard issue' in IE and Edge. The only difference I can see is the issue now appears in Chrome too.
> 
> The problem I'm facing is that I'm trying to fix legacy resources which were built on easeljs-0.7.1_14.5.30.min.js. I was able to fix the touch issue by appending your new Touch.js class to this file (overwriting the old Touch class).
> When I use the new createJS library certain features in the resources break (due to deprecated functions I expect). For this reason do you have just the modified Touch.js code so I can append that to the old easel library I'm using.

The exact problem is using the iframe and using the mouse? on the touch screen? or on the desktop computer?

**Comment by IestynBJones** [comment]
The resource works fine with a mouse, on a touchscreen and using keyboard when not in an iFrame on Safari, Chrome, IE and Edge (I've tested on iPad, windows surface and windows desktop, Android tablet). 
However when the resource is in an iFrame touch and mouse interactions still work but the keyboard doesn't in Edge and IE (tested on Windows surface keyboard and Windows desktop). When I  added your touch.js the keyboard events also broke down in Chrome.

**Comment by dijitaletkinlikler** [comment]
Yes, iframe only causes this. It does not detect the keyboard when there is an iframe. I have no idea for now I will ask Danzen. If I find an answer, I will post it here.

**Comment by dijitaletkinlikler** [comment]
> The resource works fine with a mouse, on a touchscreen and using keyboard when not in an iFrame (tested with Safari, Chrome, IE and Edge on iPad, windows surface and windows desktop, Android tablet).
> However when the resource is in an iFrame, touch and mouse interactions still work but the keyboard doesn't in Edge and IE (tested on Windows surface keyboard and Windows desktop). When I added your touch.js the keyboard events also broke down in Chrome.
> 
> So this resource, which is loaded into an iFrame exhibits the issue. Try using the arrow keys in IE or Edge: https://www.echalk.co.uk/info/ItJustWorks/resources/tetrisTable/tetrisTable.html

var testWindow = window.parent || window;
testWindow.addEventListener ("keyup", testCapture, false);

function testCapture (e) {
    
    
}

I found a solution like this on the internet. I think this is not related to the createjs library.
"Uncaught DOMException: Blocked a frame with origin" null "from accessing a cross-origin frame." to avoid this error, run with localhost or run on a server.

**Comment by IestynBJones** [comment]
Thank you dijitaletkinlikler. That was really useful. I was able to implement a solution using code along those lines.

var testWindow = window.parent ;
testWindow.removeEventListener("keydown", this.stage_keyDown.bind(this), false);
testWindow.addEventListener("keydown", this.stage_keyDown.bind(this), false);

testWindow.removeEventListener("keyup", this.stage_keyUp.bind(this), false);
testWindow.addEventListener("keyup", this.stage_keyUp.bind(this), false);

Perhaps this is a nicer way of recursing up through nested iFrames to get to the top; but my javascript skills aren't up to it.

**Comment by danzen** [comment]
Hey folks, @dijitaletkinlikler has worked out a way to handle double touch issues without the timeout I added a while back https://github.com/CreateJS/EaselJS/issues/997#issuecomment-547051940.  So we have removed that code and adjusted our CreateJS as follows:

`	
Touch._IE_handleEvent = function(stage, e) {
		if (!stage) { return; }
		if (stage.__touch.preventDefault) { e.preventDefault && e.preventDefault(); }
		var type = e.type;
		var id = e.pointerId;
		var ids = stage.__touch.activeIDs;

		if (type === "MSPointerDown" || type === "pointerdown") {
			if (e.srcElement != stage.canvas) { return; }
			ids[id] = true;
			this._handleStart(stage, id, e, e.pageX, e.pageY);

            // Added by Ferudun Vural - tested by Dan Zen
            // only enables or disables events when switching between touch and mouse
            // does not affect every touch
            switch(e.pointerType) {
              case 'mouse':
                stage.enableDOMEvents(true);
                break;
              case 'touch':
                stage.enableDOMEvents(false);
                break;
              case 'pen':
                break;
              default:
                break;
            }

		} else if (ids[id]) { // it's an id we're watching
`
Our latest version is at https://zimjs.org/cdn/1.2.4/createjs.js and https://zimjs.org/cdn/1.2.4/createjs_doc.js  I can see if I can figure out how to do a pull request if that is of interest.

**Comment by owendwyer** [comment]
Hi guys,

as I  said  before, I don't like this solution.  But I agree that it works.  

Contrary to my previous comment, listeners aren't being added/removed on each event, so there aren't any problems with this.  However, I still think it's untidy as stage.enableDOMEvents is still called on every touch/click.

Also, with this line
`canvas.style["-webkit-tap-highlight-color"] = "transparent";`
I don't think this should be set in the library as it's non-standard [see here](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-tap-highlight-color).  It does solve the problem, but it should be an application specific choice, not a universal one.  So I think it would be better not to include the line, and instead just to call it in each application - after you call 
`new createjs.Stage();` 
you can call 
`document.getElementById("myCanvas").style["-webkit-tap-highlight-color"] = "transparent";`

**Comment by owendwyer** [comment]
Also, I think at some point we need to talk about what we're doing here and what the future is for this library.  This thread has multiple fixes for different issues and they need to be organized properly.

I don't know how many people are still following this or how heavily invested anyone is with this library.  But I'm still using it and need it to be maintained for years to come.

**Comment by danzen** [comment]
@owendwyer and others there certainly may be a better solution for the double touch.  This is how I tested and came to the conclusion:

```
p.enableDOMEvents = function(enable) {
console.log("arriving");
	if (enable == null) { enable = true; }
	var n, o, ls = this._eventListeners;
	if (!enable && ls) {
console.log("one");
		for (n in ls) {
			o = ls[n];
			o.t.removeEventListener(n, o.f, false);
		}
		this._eventListeners = null;
	} else if (enable && !ls && this.canvas) {
console.log("two");
		var t = window.addEventListener ? window : document;
		var _this = this;
		ls = this._eventListeners = {};
		ls["mouseup"] = {t:t, f:function(e) { _this._handleMouseUp(e)} };
		ls["mousemove"] = {t:t, f:function(e) { _this._handleMouseMove(e)} };
		ls["dblclick"] = {t:this.canvas, f:function(e) { _this._handleDoubleClick(e)} };
		ls["mousedown"] = {t:this.canvas, f:function(e) { _this._handleMouseDown(e)} };

		for (n in ls) {
			o = ls[n];
			o.t.addEventListener(n, o.f, false);
		}
	}
};
```
and noticed that while the function gets called each touch, "one" and "two" don't run each touch but only when going from a click to a touch or back again.  For most interactions, it is a function call with what should be a quick if statement that goes nowhere.  I thought that was better than applying a timeout and extra events for each touch.  Other solutions are welcome.

With respect to the 

`canvas.style["-webkit-tap-highlight-color"] = "transparent";`

we might "reverse bill" it... so leave it in and if a developer wants it then they can add a different setting to their app.  I do not want to tell students and kids that they need to add this line so clicks don't flash on touchscreens.   If it is not wanted, we could just add it to ZIM but I don't think it will do any harm being in CreateJS.  Again, other solutions welcome.

**Comment by danzen** [comment]
Okay.  We had an issue with our solution code mentioned above. On Chrome we could not drag-select the text on the page if Touch was turned on with allowDefault false.  In looking into this it seems the solution to all of this is to add Chrome (and Firefox as it seems to be fine) to the **Touch._IOS_enable(stage);** rather than the **Touch._IE_enable(stage);** 

This seems to fix the pressdrag, the swipe select and the duplicate tap event issue.  @dijitaletkinlikler has tested, I have tested - seems good.  But before we update the CreateJS CDN we will see if some of you can test this file for us:

https://zimjs.com/cdn/1.3.3/createjs_doc_test.js

This would be on touch screens on Chrome and Firefox - check for lack of dragging, accidental double tap and text selection.  Here is a test page https://zimjs.com/test2/select.html

**Comment by danzen** [comment]
Okay. We had an issue with our solution code mentioned above. On Chrome we could not drag-select the text on the page if Touch was turned on with allowDefault false. In looking into this it seems the solution to all of this is to add Chrome, (Firefox and Edge as they seem good too) to the 

Touch._IOS_enable(stage); 

rather than the 

Touch._IE_enable(stage); 

This seems to fix the pressdrag, the swipe select and the duplicate tap event issue. @dijitaletkinlikler has tested, I have tested - seems good. But before we update the CreateJS CDN we will see if some of you can test this file for us:  https://zimjs.com/cdn/1.3.3/createjs_doc_test.js

This would be on touch screens on Chrome and Firefox - check for proper dragging, only one tap event and text selection. Here is a test page https://zimjs.com/test2/select.html.

We would rename the Touch._IOS_etc to just Touch._etc as it is more generic now.  Not sure if older versions of Chrome, Firefox and Edge needed to be run on the _IE side with msPointerEvents, etc.  So will leave a legacy parameter in the Touch.enable(stage, singleTouch, allowDefault, legacy) to go back to the old way.  Suggestions welcome.

**Comment by nickvaras** [comment]
For those still struggling with touch weirdness, what worked for me was to just replace `(window.navigator['msPointerEnabled']`  on isSupported() and then, on _IE_enable(),   drop the `if (window.navigator["pointerEnabled"] === undefined` by adding a `&& false) {` so it never executes and always proceeds to the else case.
